---
- hosts: localhost
  vars:
    resource_group: n8n_g1_4
    password: 2022Simplon!
    fqdn: n8ng14
    local: francecentral
    vnet_name: vnet
    bastion_name: bastion
    psql_server_name: psql4
    database_name: n8ndb
    vm_app_name: vmapp
    size: Standard_DS1_v2
    admin_name: noa
    image_offer: UbuntuServer
    image_publisher: Canonical
    image_sku: '18.04-LTS'
    image_version: latest
  connection: local
  tasks:
  - import_tasks: ../models/network_model.yml
  - import_tasks: ../models/vms_model.yml
