---
# Creation ressources groupe1

- hosts: localhost
  vars:
    rg: mercredi_test_4
  connection: local
  tasks:
    - name: Création du ResourceGroup
      azure_rm_resourcegroup:
        location: eastus
        name: "{{ rg }}"
    - name: Création du VNet
      azure_rm_virtualnetwork:
        resource_group: "{{ rg }}"
        name: vnetbr4
        address_prefixes: "10.0.0.0/16"
    - name: Création du Subnet
      azure_rm_subnet:
        resource_group: "{{ rg }}"
        name: subnetg1
        address_prefix: "10.0.2.0/24"
        virtual_network: vnetbr4
    - name: Création de l'IP publique de la VM
      azure_rm_publicipaddress:
        resource_group: "{{ rg }}"
        allocation_method: Static
        name: ipvm
        sku: standard
      register: ippub
    - debug:
        msg: "Adresse IP Publique: {{ ippub.state.ip_address }}"
    - name: Création du NSG
      azure_rm_securitygroup:
        resource_group: "{{ rg }}"
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: web
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
          - name: webplus
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 1003
            direction: Inbound
          - name: websecur
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1004
            direction: Inbound
    - name: Network interface
      azure_rm_networkinterface:
        resource_group: "{{ rg }}"
        name: interface
        virtual_network: vnetbr4
        subnet: subnetg1
        public_ip_name: ipvm
        security_group: myNetworkSecurityGroup
    - name: Creation de la VM
      azure_rm_virtualmachine:
        resource_group: "{{ rg }}"
        name: vmtest
        vm_size: Standard_DS1_v2
        admin_username: adminuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/adminuser/.ssh/authorized_keys
            key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIA63uZA2mphnWmK/fD+J0IL2e3Th2BzbZ7RgZQQwy12Qfr2ObceXQgWtsPf41XfIudWqTNsw1J3B2nlyC7V72rTpBZP0O2cYHsRsz0kQXefWMHsgIfBNZKooLY7ZN0S/ay76VO8rAT/wgEEmtne1zHC6pv+V69gqVQr22JujdEJiwqEHOtV3x1X1eM3B8+ZM/ugoUrnrkLc18LKPaAUxvi4Bta4t1ILSHRZqvJdpf8YPH02PT2HCQWPNksYcgOeoUXQrf7gCD8mkL4aAO5ogQyi5q/XyN65CsYJLO0J4688W8r5hAJyUCQgx+KbhuoVdBaOGmFyBwVNjR7TODnQPX
        network_interfaces: interface
        custom_data: "{{ lookup('file', 'cloud-init.yml') }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: '18.04-LTS'
          version: latest
