---

- hosts: localhost
  connection: local

  vars:
    resource_group: mercredi_test_20
    vnet_name: myVNet
    subnet_name: mySubnet
    location: eastus
    psql_server_name: psqlserver-20

  tasks:
    - name: Création du ResourceGroup
      azure_rm_resourcegroup:
        location: "{{ location }}"
        name: "{{ resource_group }}"

    - name: Création du VNet
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.0.0.0/16"

    - name: Création du Subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.0.2.0/24"
        virtual_network: "{{ vnet_name }}"

    - name: Création de l'IP publique de la VM
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: ipvm
        sku: standard
      register: ippub
    - debug:
        msg: "Adresse IP Publique VM : {{ ippub.state.ip_address }}"

    - name: Création du NSG
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: web
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
          - name: webplus
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 1003
            direction: Inbound
          - name: websecur
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1004
            direction: Inbound

    - name: Network interface
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: vmapp_interface
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: ipvm
        security_group: myNetworkSecurityGroup

    - name: Creation d'un serveur postgreSQL
      azure_rm_postgresqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ psql_server_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
        location: eastus
        storage_mb: 5120
        enforce_ssl: False
        storage_autogrow: True
        admin_username: n8n
        admin_password: 2022Simplon! 

    - name: Creation de la base de donnée postgreSQL
      azure_rm_postgresqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ psql_server_name }}"
        name: n8ndb

    - name: Creation regle firewall pour VM
      azure_rm_postgresqlfirewallrule:
        resource_group: "{{ resource_group }}"
        server_name: "{{ psql_server_name }}"
        name: regle1
        start_ip_address: "{{ ippub.state.ip_address }}"
        end_ip_address: "{{ ippub.state.ip_address }}"

    - name: Création de la VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: vmapp
        vm_size: Standard_DS1_v2
        admin_username: adminuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/adminuser/.ssh/authorized_keys
            key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIA63uZA2mphnWmK/fD+J0IL2e3Th2BzbZ7RgZQQwy12Qfr2ObceXQgWtsPf41XfIudWqTNsw1J3B2nlyC7V72rTpBZP0O2cYHsRsz0kQXefWMHsgIfBNZKooLY7ZN0S/ay76VO8rAT/wgEEmtne1zHC6pv+V69gqVQr22JujdEJiwqEHOtV3x1X1eM3B8+ZM/ugoUrnrkLc18LKPaAUxvi4Bta4t1ILSHRZqvJdpf8YPH02PT2HCQWPNksYcgOeoUXQrf7gCD8mkL4aAO5ogQyi5q/XyN65CsYJLO0J4688W8r5hAJyUCQgx+KbhuoVdBaOGmFyBwVNjR7TODnQPX
        network_interfaces: vmapp_interface
        custom_data: "{{ lookup('file', 'cloud-init.yml') }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: '18.04-LTS'
          version: latest
