#cloud-config

groups:
  - admingroup: [root,sys]
  - cloud-users
  - docker

users:
  - default

  - name: noa
    gecos: Noa
    passwd: "$6$jCheUtQqsSkup4VR$q8xtBuY8TG.j0PgJ/264dlBM5P7/v1hymZWfq39CrLnTHokfePtkWFBWTNJLvrlMyaS7ehSqZN.7Sm6qvT84T1"
    primary_group: noa
    groups: sudo, users, admin, admingroup
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ22kbj03g37Nc50Pt4CiPGR5mkNYisvfN7xu4iGZjqD

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages_update: true
packages_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - sudo docker pull n8nio/n8n
  - docker run -it --rm --name n8n -p 80:5678 -e DB_TYPE=postgresdb -e DB_POSTGRESDB_DATABASE=n8ndb -e DB_POSTGRESDB_HOST=psqlserver-20.postgres.database.azure.com -e DB_POSTGRESDB_PORT=5432 -e DB_POSTGRESDB_USER=n8n@psqlserver-20 -e DB_POSTGRESDB_SCHEMA=public -e DB_POSTGRESDB_PASSWORD=2022Simplon! -e GENERIC_TIMEZONE="Europe/Paris" -e TZ="Europe/Paris" -v /var/lib/n8n:/home/node/.n8n n8nio/n8n n8n start
