---

- hosts: localhost
  vars:
    rg: test_thomas_app_gateway
    vnet: vnettest_app_gateway
    subnet_ag: subnet_app_gateway
  connection: local

  tasks:
    - name: Creation du groupe de ressources
      azure_rm_resourcegroup:
        location: eastus
        name: "{{ rg }}"
    - name: Creation du reseau virtuel
      azure_rm_virtualnetwork:
        resource_group: "{{ rg }}"
        name: "{{ vnet }}"
        address_prefixes: "10.0.0.0/16"
    #creation d'un subnet unique pour AG
    - name: Creation subnet AG
      azure_rm_subnet:
        resource_group: "{{ rg }}"
        name: "{{ subnet_ag }}"
        virtual_network_name: "{{ vnet }}"
        address_prefix_cidr: "10.0.1.0/24"
      register: subnetAG
    - name: Creation subnet VM
      azure_rm_subnet:
        resource_group: "{{ rg }}"
        name: subnet_VM
        virtual_network_name: "{{ vnet }}"
        address_prefix_cidr: "10.0.2.0/24"
      register: subnetVM
# creation ip publique AG, pas d'ip publique pour la VM
    - name: Creation de l IP publique AG
      azure_rm_publicipaddress:
        resource_group: "{{ rg }}"
        allocation_method: Static
        name: ipAG
        sku: standard
      register: ipAG
    - debug:
        msg: "Adresse IP AG: {{ ipAG.state.ip_address }}"
    - name: Creation du groupe de sécurité azure SSH
      azure_rm_securitygroup:
        resource_group: "{{ rg }}"
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: web
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
          - name: webplus
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 1003
            direction: Inbound
          - name: websecur
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1004
            direction: Inbound
    - name: Network interface AG
      azure_rm_networkinterface:
#        request_routing_rules:
#          backend_address_pool: nom ressource...
# à voir pour créer les règles de backend pool 
        resource_group: "{{ rg }}"
        name: interface
        virtual_network: "{{ vnet }}"
        subnet: "{{ subnet_ag }}"
        public_ip_name: ipAG
        security_group: myNetworkSecurityGroup
    - name: Network interface VM
      azure_rm_networkinterface:
        resource_group: "{{ rg }}"
        name: interface
        virtual_network: "{{ vnet }}"
        subnet: subnet_VM
#config pour aucune ip publique pour la vm
        create_with_security_group: False
        ip_configurations:
          - name: regle_ip
            primary: True
        security_group: myNetworkSecurityGroup
    - name: Creation de la VM
      azure_rm_virtualmachine:
        resource_group: "{{ rg }}"
        name: vmtest
        subnet_name: subnet_VM
        vm_size: Standard_DS1_v2
        admin_username: thomas
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/thomas/.ssh/authorized_keys
            key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQtaIPgHDrA4olC0mkDwPZqDA6ZHEVBJXUwf4kqwAHiUwnB0DtDlj0Vide0JJ56ODEEIojm3H8LExDRwxTWdFPn+JzwDVMA7xWqBBfcuykmzISXB2cTBR1AILhWIETAHtHZMqWBAZakfc5g1ik0VeQas6JAYHr0nzFdC9wO1FQJnbgoEHZERb4/Xxvxn/91GIvDqPwDRQr1OAutqUeenJyihip+US+Xnbrq/TmKKuQM+MJLrpMa2QlKoflo+7cs69q47v/W8EAx4x8RL77Woz8G5T8FvJuuPVkEcvqEUtb9cbnDaytSp02hYAYstsgW01cRgIVHXta5aK5o/0cmtU0vmMuECWZk18bDw3JkTgBzOKZ/cmJl1ur3qa9744tBKxu31LUbyOVYb92pc72s4lAfUESjPSiqSJ4nQ8iuGuwDDt3RVJEXKUCtnjDxGO8Qa8dgaK/LOEWCRTfLZ9yxo0ytEKCelVC2fVhBv1pJQubYb8R8IkqmcyoZ2+b5iOiVSIOgfijnEAh2aOTX/uTgcDNKYxxNpfTe0e+hXRfP/LL4QF+BF43uXwEEfw42I3X9jfO7Usd7LQndsIiA9B93gv87CtdoOIUCpRt4b4t1Q2d0cBhlS/YPqixauxMvpXJcUDISwoVCfmCjMNposBbIiyH4vrq91P4apb1u7oTmrNaTQ== thomas@host
        network_interfaces: interface
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: '18.04-LTS'
          version: latest
    - name: Creation de la ressource Application Gateway
      azure_rm_appgateway:
        resource_group: "{{ rg }}"
        name: myAppGateway
        sku:
          name: standard_small
          tier: standard
          capacity: 2
        gateway_ip_configurations:
          - subnet:
              id: #subscriptions/a1f74e2d-ec58-4f9a-a112-088e3469febb/resourceGroups/test_thomas_app_gateway/providers/Microsoft.Network/virtualNetworks/vnettest_app_gateway/subnets/subnet_app_gateway
              name: "{{ subnet_ag }}"
              virtual_network_name: "{{ vnet }}"
        frontend_ip_configurations:
          - subnet:
              id: #subscriptions/a1f74e2d-ec58-4f9a-a112-088e3469febb/resourceGroups/test_thomas_app_gateway/providers/Microsoft.Network/virtualNetworks/vnettest_app_gateway/subnets/subnet_app_gateway
              name: "{{ subnet_ag }}"
              virtual_network_name: "{{ vnet }}"
            publip_ip_address: #reference de la ressource Public IP
            name: configuration_ip_frontend
        frontend_ports:
          - port: 90
            name: port_frontend_AG
        backend_address_pools:
          - backend_addresses:
              - ip_address: #adresse_ip_machine_privée
            name: pool_adresse_backend
        backend_http_settings_collection:
          - port: 80
            protocol: http
            cookie_based_affinity: enabled
            name: reglage_http
        http_listeners:
          - frontend_ip_configuration: configuration_ip_frontend
            frontend_port: port_frontend_AG
            name: ecoute_AG_http
            protocol: "http"
        request_routing_rules:
          - rule_type: Basic
            backend_address_pool: pool_adresse_backend
            backend_http_settings: reglage_http
            http_listener: ecoute_AG_http
            name: regle_http
        gateway_state: started